### ISSUE TITLE
Browser see Rezact as React when using Vanilla JS

### ISSUE THREAD

**Issue by neghi14** [Rezact/Rezact#46]
**Describe the bug**
All the times I've used Rezact, I have with typescript. I decided to use with vanilla js to see if it works just the same but even with a one to one copy of the vite configuration files, the browser seems to mistake my code for react and thus, nothing is displayed on the browser.

**To Reproduce**
1. Create a new vite project using vanilla js template
2. copy vite configuration
![Screenshot 2023-10-15 101041](https://github.com/Rezact/Rezact/assets/106474028/749e49f4-6ae6-41a6-98ed-228bc3a30450)
 3.  Config main.ts appropriately 
![Screenshot 2023-10-15 102443](https://github.com/Rezact/Rezact/assets/106474028/595fa065-7222-4dc7-a044-2520727dda54)
4. Create Jsx files
![Screenshot 2023-10-15 101229](https://github.com/Rezact/Rezact/assets/106474028/83b22df5-e5cc-4cf3-85e0-ad2576c0693e)
5. Start vite server
![Screenshot 2023-10-15 101129](https://github.com/Rezact/Rezact/assets/106474028/94b59f83-af2b-4ddf-b337-ee5a488305fe)
6. I get a blank screen when i open my browser
![Screenshot 2023-10-15 101144](https://github.com/Rezact/Rezact/assets/106474028/a837a1cd-b919-429a-accb-311d6641cee7)
7. Checking the console gives the error "React not Defined"
![Screenshot 2023-10-15 101159](https://github.com/Rezact/Rezact/assets/106474028/8363cf44-313b-4533-bcc1-d0cce84c2d34)

**Expected behavior**
I expected it to work as it would have using typescript.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version: 118.0.5993.70

**Additional context**
Note: I used vanilla jsx, so therefore there was no tsconfig file. My suspicions are substituting tsc for another bundler may do the trick but I'm not too certain about that.

**Comment by zachlankton** [comment]
It looks like you are missing some config in vite:

```js
esbuild: {
      jsxFactory: "xCreateElement",
      jsxFragment: "xFragment",
    },
```

![image](https://github.com/Rezact/Rezact/assets/2927894/446b73c3-9107-4b7e-bc37-a13b5f533f64)

**Comment by neghi14** [comment]
Works now, Thank you.
